### ISSUE TITLE
I get an error when i try to update. Traceback info: assert (post.id == 2) AssertionError

### ISSUE THREAD

**Issue by EXboys** [fernandojunior/python-sqlite-orm#12]
here is my code:

 post = Post('testMessage').save()
    # print post.id
    assert (post.id == 2)
    # post.text = 'Hello rrr'
    post.update()

**Comment by aberkowitz** [comment]
@xiaocaiyidie:
It looks like your error is happening on the 3rd line of your code where you try to verify that the post's id is 2. Is there a reason why you want to check the post's id?

```python
 assert (post.id == 2)
```

**Comment by EXboys** [comment]
I want to Update the date in sqlite3 which id is 2
and i do this just want to learn how to use update command in python-sqlite-orm
thanks!

**Comment by fernandojunior** [comment]
Hey @xiaocaiyidie, here's how you can read an object from SQLite:
```py

# using default database
post = Post.manager().get(id=1)

# from another database
db2 = Database('db2.sqlite')
post = Post.manager(db=db2).get(id=1)
```

**Comment by EXboys** [comment]
thanks!
